Repository Visual-Behavior/aloception-oss, pull requests merged in 2022-12, with the labels that each got.

#281 load model from run_id
  alonet/common/weights.py
Labels: good first issue, alonet, alobugdays

#299 Detach tensors not used for backprop
  alonet/detr/train.py
Labels: enhancement, quick-fix

#313 Delete action
  .github/workflows/action.yml
Labels: bug, invalid, quick-fix

#259 Alobugsdays - Aloception Logo
  README.md
  docs/_sources/getting_started/getting_started.rst.txt
  docs/getting_started/getting_started.html
  docsource/source/getting_started/getting_started.rst
  images/aloception-oss.jpg
  images/aloception.png
Labels: documentation, enhancement, good first issue, invalid, quick-fix, alobugdays
